name: Build and Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

env:
  AWS_REGION: us-east-1
  S3_BUCKET: spaceapps2023-frontend

jobs:

  build-and-upload-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: 'Install Dependencies'
      run: npm install
      working-directory: './frontend'

    - name: Build React App
      env:
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
      run: npm run build
      working-directory: './frontend'

    - name: Upload to S3
      run: |
        aws s3 sync frontend/build/ s3://${{ env.S3_BUCKET }}/
      
    - name: 'Invalidate CloudFront Distribution'
      run: |
        aws cloudfront create-invalidation --distribution-id E2E8D3KBJXR07U --paths "/*"